[general]
import = [
  "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[window]
decorations="Transparent"
opacity=0.85
blur=true

[font]
normal = { family = "MesloLGL Nerd Font Mono", style = "Regular" }
size = 12

[colors.primary]
background = '#000000'

