[general]
  import = [
      "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
  ]

[window]
  decorations="Transparent"
  opacity=0.7
  blur=true

[font]
  normal = { family = "MesloLGL Nerd Font Mono", style = "Regular" }
  size = 12
